{{- if not .Values.kubeconfig.sealedSecret }}
apiVersion: v1
data:
  {{- with .Values.kubeconfig.files }}
  {{- toYaml . | b64enc | nindent 2 }}
  {{- end }}
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-kubeconfigs
type: Opaque
{{- end }}