apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: sealed-secrets-ui
  name: sealed-secrets-ui-svc
  namespace: sealed-secrets-ui
spec:
  ports:
    - name: http
      port: 5000
  selector:
    app.kubernetes.io/instance: sealed-secrets-ui
    app.kubernetes.io/name: sealed-secrets-ui