{{- if and (eq .Values.authFiles.enabled true) (eq .Values.authFiles.sealedSecret false) }}
apiVersion: v1
data:
  {{- range $k, $v := .Values.authFiles.files }}
  {{ $k }}: {{ $v | b64enc}}
  {{- end }}
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-authfiles
type: Opaque
{{- end }}