apiVersion: v1
entries:
  sealed-secrets-ui:
  - apiVersion: v2
    appVersion: v0.1.2
    created: "2023-03-17T11:08:25.303178356-04:00"
    description: A Helm chart for a Sealed Secrets web interface
    digest: 1ad2a198ddfba571fe29ebe6558e8ea61bb00a45799ed47712334f8baf7cf3ca
    name: sealed-secrets-ui
    type: application
    urls:
    - https://noahburrell0.github.io/sealed-secrets-ui/chart/packages/sealed-secrets-ui-0.1.0.tgz
    version: 0.1.0
generated: "2023-03-17T11:08:25.301091499-04:00"
